# Generated by Django 5.0.1 on 2024-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
