# Generated by Django 5.0.1 on 2024-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Visitor_came_from',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
