# Generated by Django 5.0.1 on 2024-03-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_remove_contact_visitor_came_from_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Last_visited_pages',
            new_name='CF7VPUT_VISITED_Details',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Lead_ID',
            new_name='_serial_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile_Number',
            new_name='_time',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Referral_information_field',
            new_name='referral_Information_field',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Time',
            new_name='tel',
        ),
    ]
